/* Tawakkul — English language pack */
window.LANG_EN = {
ui: {
  tabs: { chat: 'Talk', dhikr: 'Dhikr', weg: 'Path', remind: 'Reminders', wissen: 'Knowledge' },
  lblEinfach: 'Explained simply', lblKoran: 'From the Quran', lblHadith: 'The Prophet ﷺ said',
  welcomeT: 'As-salamu alaykum. I am your companion for tawakkul — trusting in Allah.',
  welcomeE: 'Write me whatever is on your mind — a worry, an intrusive thought, a question in your heart. I answer with the Quran and the authentic Sunnah, explained so simply that every heart understands. Everything stays on your device only.',
  chipsTitel: 'Or tap a thought that troubles you right now:',
  chips: ['Allah doesn’t give me what I want','I have money worries','I’m afraid of the future','My dua is not answered','I have terrible intrusive thoughts','I feel alone','I made mistakes','Why is this happening to me?','Others have a nice life and I only have problems','I keep catching myself in old thoughts','What does SubhanAllah actually mean?','It would never work out for me anyway','How do I pray the night prayer?'],
  placeholder: 'Write me your thought …',
  statisch: [
    ['.motto', '“Whoever relies on Allah — He is enough for him.” — 65:3'],
    ['#clearChat', 'Clear history'],
    ['#view-dhikr h2.sect', 'Dhikr & Istighfar'],
    ['#view-dhikr .sub', 'Choose a dhikr and tap the circle. Your counter is saved.'],
    ['#verstehBtn', 'What am I saying? · Understand'],
    ['#reset', 'Reset'],
    ['#view-weg h2.sect', 'My Path — Daily Checklist'],
    ['#view-weg .sub', 'Small steps, every day. The list starts fresh at midnight.'],
    ['#view-remind h2.sect', 'Remembering Allah'],
    ['#view-remind .sub', 'For the moment when the heart feels tight.'],
    ['#rNext', 'New reminder'],
    ['#ortBtn', 'Use my location'],
    ['#pushTest', 'Send test push'],
    ['#pushKopie', 'Copy channel'],
    ['#wissenHome h2.sect', 'What would you like to do right now?'],
    ['#wissenHome .sub', 'Tap a card for a simple step-by-step guide with the right duas in the right place.']
  ],
  hinweis: 'Note: the guides and libraries below are being translated — they are currently shown in German. The chat, dhikr and checklist are fully in English.',
  duaSuche: 'Search: worry, debt, children, healing …',
  hadithSuche: 'Search: patience, mercy, provision, dhikr …',
  weg: {
    gebete: 'Prayed my 5 daily prayers (as well as I could)', morgen: 'Did my morning adhkar', duha: 'Prayed two rakʿas of Duha in the morning', abend: 'Did my evening adhkar',
    istighfar: 'Said istighfar 70×', koran: 'Read or listened to some Quran (5 minutes count!)', dank: 'Named 3 things I thank Allah for',
    gedanke: 'Caught a bad thought about Allah and reversed it', yaqin: 'Replaced “that will never happen” with “in sha Allah — Allah can do anything”',
    gutes: 'Did something good for someone or gave a kind word', sadaqa: 'Gave sadaqa — even tiny, a smile counts', dua: 'Made a sincere dua for myself and others'
  },
  wegFertig: 'All done — may Allah accept it from you! This is what a day that changes your heart looks like.',
  wegVon: ' of ', wegHeute: ' done today.',
  ziel: 'Goal: ', heute: 'Today: ', dhikrWort: ' dhikr · ', gestern: 'Yesterday: ', serie: ' days in a row, ma sha Allah!',
  dhikrDe: {
    istighfar: 'I ask Allah for forgiveness', subhan: 'Allah is perfect — He never makes mistakes', alhamdu: 'All praise and thanks belong to Allah',
    akbar: 'Allah is greater — than everything', hasbuna: 'Allah is enough for us — the best Guardian', lahawla: 'No change and no power — except through Allah',
    salawat: 'O Allah, bless Muhammad ﷺ', lailaha: 'Nothing deserves worship except Allah'
  }
},
erinnerungen: [
  { x: 'Have you remembered Allah in the last hour? Now is a good moment: Astaghfirullah.', r: '' },
  { x: 'Whoever relies on Allah — He is enough for him.', r: 'Quran 65:3' },
  { x: 'In the remembrance of Allah hearts find rest.', r: 'Quran 13:28' },
  { x: 'Do not despair of the mercy of Allah.', r: 'Quran 39:53' },
  { x: 'Allah says: I am as My servant thinks of Me. Think well of Him — right now.', r: 'Bukhari 7405' },
  { x: 'With hardship comes ease.', r: 'Quran 94:6' },
  { x: 'Tie your camel — and trust in Allah.', r: 'Tirmidhi 2517' },
  { x: '“Be!” — and it is. Your wish is not too big for Him.', r: 'Quran 36:82' },
  { x: 'Don’t say “that will never happen”. Say: “In sha Allah — my Lord can do anything.”', r: '' },
  { x: 'Call upon Me; I will respond to you.', r: 'Quran 40:60' },
  { x: 'Your dua is never lost: now, later, or as a treasure in the Hereafter.', r: 'Ahmad 11133' },
  { x: 'Have you made a checkmark on your checklist today?', r: '' }
],
db: {
  nichtgeben: { prio: 10,
    phrasen: ["doesn't give me","does not give me","won't give me","never gives me","allah forgot me","forgotten me","doesn't love me","does not love me","hates me","old thoughts","caught myself","keep thinking","again these thoughts"],
    worte: ['deprived','overlooked'],
    antworten: [
      { t: 'No — Allah does not hold back because He dislikes you. He chooses a better time or a better gift for you.',
        e: 'A good father says no to sweets before dinner — not because he doesn’t love his child, but BECAUSE he loves him. The child sees only the candy; the father sees the stomach ache. You see only today; Allah sees your whole life and Paradise beyond it. “Not yet” is not “no”. And remember: your hands never return empty from Allah — every dua brings you the thing itself, something better, a harm removed, or a treasure saved for the Day you need it most.',
        q: { x: '… Perhaps you hate a thing and it is good for you; and perhaps you love a thing and it is bad for you. And Allah knows, while you know not.', r: 'Quran 2:216' },
        h: { x: 'Allah says: “I am as My servant thinks of Me.”', r: 'Hadith Qudsi — Sahih al-Bukhari 7405' },
        a: { text: 'Think WELL of Allah right now: name 3 things He already gave you and say Alhamdulillah for each.', dhikr: 'alhamdu', btn: '33× Alhamdulillah' } },
      { t: 'You caught yourself — excellent! That is exactly how a heart is retrained.',
        e: 'Old thoughts are like a trodden path in the snow: your feet walk it automatically. Every time you catch the thought and flip it — “No, Allah DOES want to give me; He chooses the time and the form” — you stamp a new path. The first fifty times are hard. Then your heart walks the new path by itself. Catching yourself is not failure. It is the training.',
        q: { x: 'Indeed, Allah will not change the condition of a people until they change what is in themselves.', r: 'Quran 13:11' },
        h: { x: 'Faith wears out in your hearts as a garment wears out — so ask Allah to renew the faith in your hearts.', r: 'al-Hakim — sahih (al-Albani)' },
        a: { text: 'Make it measurable: tick “Caught a bad thought and reversed it” on your checklist — every day a victory.', view: 'weg', btn: 'To the checklist' } }
    ]},
  neid: { prio: 8,
    phrasen: ['others have','everyone has','everybody has','nice life','better life','no problems','why does he','why does she','why do others','and i have nothing','only i','everyone except me','luckier than me','earns more','twice as much'],
    worte: ['jealous','jealousy','envy','envious','lambo','lamborghini','ferrari','porsche','millions','million','rich','richer','penthouse','villa','rolex','luxury','instagram','tiktok'],
    antworten: [
      { t: 'Flip the thought: maybe Allah is not keeping it FROM you — maybe He is first making you READY for it.',
        e: 'A good teacher doesn’t give a third-grader the sixth-grade exam — not as punishment, but as protection. Some gifts would break us today: money before maturity breeds arrogance. Allah says He sends provision “in due measure”, because excess corrupts people (42:27). So change the question: not “why does HE have it?” but “what can I do to become ready?” — your daily checklist exists exactly for that.',
        q: { x: 'And if Allah had extended provision for His servants, they would have committed tyranny on earth. But He sends down in due measure whatever He wills.', r: 'Quran 42:27' },
        h: { x: 'There is no envy except in two: a man whom Allah gave wealth and he spends it in the way of truth, and a man whom Allah gave wisdom and he acts on it and teaches it.', r: 'Sahih al-Bukhari 73' },
        a: { text: 'Open your daily checklist and make the first checkmark. Becoming ready is work — start now.', view: 'weg', btn: 'To the checklist' } },
      { t: 'Do the opposite of envy: bless him. That trick frees your heart — and opens your own door.',
        e: 'You cannot pray for someone and envy him at the same time. So when you see his success, say “Barakallahu lahu — may Allah bless it for him”, then ask for YOURSELF: “O Allah, give me the same and better — halal and blessed.” The angel says about your dua for him: “Amin — and for you the same!” (Muslim 2732). His Ferrari does not empty Allah’s treasury: if every human and jinn received all they asked, His kingdom would decrease only as much as a needle takes from the sea (Muslim 2577). And remember: you compare your inside with his shop window — nobody posts the tears at 3 a.m.',
        q: { x: 'And do not wish for that by which Allah has favored some of you over others … and ask Allah of His bounty.', r: 'Quran 4:32' },
        h: { x: 'No servant prays for his brother in his absence except that the angel says: “And for you the same.”', r: 'Sahih Muslim 2732' },
        a: { text: 'Next time you see the Lambo: “Barakallahu lahu” — then ask Allah for the same and better for yourself.', dhikr: 'hasbuna', btn: '33× Hasbunallah' } }
    ]},
  rizqwunsch: { prio: 11,
    phrasen: ['want to be rich','want to get rich','wrong to want money','is it haram','bad muslim because','build wealth','feels haram'],
    worte: [],
    antworten: [
      { t: 'No — wanting wealth does NOT make you a bad Muslim. What matters is where the money sits: in the hand or in the heart.',
        e: 'The Prophet ﷺ said: “How excellent is good (halal) wealth in the hand of a righteous man!” (Ahmad 17763). ʿAbdur-Rahman ibn ʿAwf was among the richest of Arabia — and one of the ten promised Paradise. Money in the HAND of a believer builds mosques, feeds families, frees people. It only becomes dangerous when it slips into the HEART — onto the throne where only Allah may sit. So wish for wealth, work for it, ask Allah BIG for it — with the intention to do good with it. That is worship, not sin.',
        q: { x: 'But seek, through that which Allah has given you, the home of the Hereafter; and do not forget your share of this world.', r: 'Quran 28:77' },
        h: { x: 'How excellent is good wealth for a righteous man!', r: 'Musnad Ahmad 17763 — sahih' },
        a: { text: 'Set your intention now: “O Allah, give me halal wealth with which I give, help and come closer to You.” Then tie the camel: work, learn, plan.', dhikr: 'istighfar', btn: '70× Istighfar' } }
    ]},
  fluch: { prio: 11,
    phrasen: ['am i cursed','i am cursed','evil eye','black magic','someone did something to me','put a spell','got nazar'],
    worte: ['cursed','curse','sihr','hexed','nazar','jinx'],
    antworten: [
      { t: 'Stop — before fear eats you: nothing and no one can touch you without Allah’s permission. No eye, no magic, no human.',
        e: 'Yes, the evil eye is real — the Prophet ﷺ said “al-ʿayn is true” (Muslim 2188). BUT it can only act if Allah allows it (9:51). And Allah gave you a fortress stronger than any eye: the morning and evening adhkar, Ayat al-Kursi and the three protective surahs. And very important: NOT every setback is a curse! Usually it is simply a test and qadar — the path of every believer. Never go to “healers” with amulets or fortune-telling — that is the door to shirk. If genuinely concerned: do ruqya with the Quran yourself and ask a trustworthy imam.',
        q: { x: 'Say: Never will we be struck except by what Allah has decreed for us; He is our protector.', r: 'Quran 9:51' },
        h: { x: 'Say three times in the evening: “Aʿudhu bi-kalimatillahit-tammati min sharri ma khalaq” — then nothing will harm you that night.', r: 'Sahih Muslim 2708' },
        a: { text: 'Build your fortress: the morning and evening routine is the protection from the Sunnah, every day.', guide: 'morgen', btn: 'To the protection routine' } }
    ]},
  rueckschlag: { prio: 11,
    phrasen: ["nothing changes","nothing is changing","doesn't help anyway","for weeks","still the same","missed fajr","overslept","skipped dhikr","gave up again","fell back","hate myself","so weak"],
    worte: ['overslept','relapse'],
    antworten: [
      { t: 'It IS changing — just where you cannot see it: underground, at the roots.',
        e: 'Bamboo barely grows above ground for years — below, it builds a massive root system. Then it shoots up meters in weeks. Not one of your dhikr was lost: “Whoever does an atom’s weight of good will see it” (99:7). And honestly — you are using an app to come closer to Allah; the you of a month ago wouldn’t have. THAT is the root. The Prophet ﷺ said the most beloved deed to Allah is the most CONSISTENT one, even if small.',
        q: { x: 'So whoever does an atom’s weight of good will see it.', r: 'Quran 99:7' },
        h: { x: 'The most beloved deeds to Allah are the most consistent, even if small.', r: 'Sahih al-Bukhari 6464' },
        a: { text: 'Don’t do more — just don’t stop. Today only ONE checkmark. That is consistency.', view: 'weg', btn: 'To the checklist' } },
      { t: 'Two days of pause is not a crash — and self-hatred is not tawba. Just get up again, without drama.',
        e: 'The Prophet ﷺ said: “ALL children of Adam make mistakes — and the best of those who err are those who keep returning.” (Tirmidhi 2499) Not: those who never fall. Those who return. After a pause, shaytan wants only one thing: that you say “I’m too weak anyway” and quit completely. Don’t give him that. And about the overslept night prayer: whoever firmly intended to get up and overslept is written the FULL reward — and the sleep was a gift (an-Nasa’i 1787).',
        q: { x: 'And those who, when they commit an indecency or wrong themselves, remember Allah and seek forgiveness for their sins …', r: 'Quran 3:135' },
        h: { x: 'All children of Adam err, and the best of those who err are those who repent.', r: 'Tirmidhi 2499 — hasan' },
        a: { text: 'No looking back, no drama: say Astaghfirullah once and make one single checkmark today. Tomorrow another.', dhikr: 'istighfar', btn: 'Start istighfar' } }
    ]},
  kraenkung: { prio: 9,
    phrasen: ['humiliated me','made fun of me','in front of everyone','called me a failure','put me down','made me look'],
    worte: ['failure','insulted','humiliated','mocked','bullied','disrespect','boss','ridiculed'],
    antworten: [
      { t: 'His word about you is not your worth. Your worth was set by Allah — and no human can touch it.',
        e: 'The Prophet ﷺ — the best human who ever lived — was called a liar, a madman. In Ta’if they stoned him until he bled. Did that lower his rank with Allah by a dust grain? Allah raised him above all people. Remember: “Honour belongs to Allah, His Messenger and the believers” (63:8) — honour is collected from Allah, not from the boss and not from a brother. Words cannot cut your rizq, lower your rank with Allah or write your future. Answer with dignity or with silence — and let Allah handle the rest.',
        q: { x: 'And to Allah belongs the honour, and to His Messenger, and to the believers.', r: 'Quran 63:8' },
        h: { x: 'The strong one is not the one who wrestles people down; the strong one is the one who controls himself in anger.', r: 'Sahih al-Bukhari 6114' },
        a: { text: 'Hand over the hurt before it settles: 33× “La hawla wa la quwwata illa billah” — then a dua for yourself.', dhikr: 'lahawla', btn: '33× La hawla' } }
    ]},
  schlaf: { prio: 8,
    phrasen: ["can't sleep","cannot sleep","can't fall asleep","lying awake","awake at 3","racing thoughts"],
    worte: ['sleepless','insomnia','overthinking','ruminating'],
    antworten: [
      { t: 'Your head spins because it carries loads that don’t belong to it. Hand them over — then it may sleep.',
        e: 'Night rumination is trying to carry tomorrow today. But tomorrow is carried by Allah — not by you. The Prophet ﷺ taught us a hand-over for falling asleep: “O Allah, I surrender myself to You and entrust my affair to You …” (Bukhari 247). Like leaving your luggage at reception: tell Allah every single worry, lay it before Him — then recite Ayat al-Kursi (a guardian protects you until morning, Bukhari 2311) and the three protective surahs into your hands. Hearts find rest in the remembrance of Allah (13:28) — especially at 2 a.m.',
        q: { x: 'Those who believe and whose hearts find rest in the remembrance of Allah. Verily, in the remembrance of Allah do hearts find rest!', r: 'Quran 13:28' },
        h: { x: '“O Allah, I surrender myself to You and entrust my affair to You …” — whoever says it and dies that night, dies upon the fitrah.', r: 'Sahih al-Bukhari 247' },
        a: { text: 'Open the “Before sleeping” guide — five steps, and your head may let go.', guide: 'schlaf', btn: 'To the sleep guide' } }
    ]},
  rizq: { prio: 6,
    phrasen: ['no money','little money','no job','lost my job','rent is due','broke again'],
    worte: ['money','salary','wage','job','work','unemployed','debt','debts','rent','bill','bills','poor','poverty','earn','business','clients','finances','broke','application','rejected','fired','interest','loan','mortgage'],
    antworten: [
      { t: 'Your rizq was written long ago. No human on earth can take what Allah has assigned to you.',
        e: 'Before you were born, Allah already wrote what you will receive — every loaf, every franc. Look at the birds: no account, no boss, no plan. They just fly out in the morning — and Allah feeds them. Your task is only the flying out: work, stay honest, make dua. The feeding is Allah’s task. It never was yours.',
        q: { x: 'And there is no creature on earth but that upon Allah is its provision.', r: 'Quran 11:6' },
        h: { x: 'If you relied on Allah as He truly deserves, He would provide for you as He provides for the birds: they leave hungry in the morning and return full in the evening.', r: 'Tirmidhi 2344 — hasan sahih' },
        a: { text: 'Do both: tie your camel (work, apply, plan) AND trust. And make much istighfar today — it opens doors of provision.', dhikr: 'istighfar', btn: '70× Istighfar' } },
      { t: 'A tight wallet does not mean Allah forgot you. Even the tightness is measured by Ar-Razzaq, the Provider.',
        e: 'Allah promises something astonishing: whoever fears Him and trusts Him, He gives a way out — and provision from where he NEVER expected. Not from where you plan it. From where you don’t expect it. Your rizq does not hang only on your job or your account. Allah’s ways are more than your bills. Nuh told his people: make istighfar — then Allah sends rain, wealth and children (71:10–12).',
        q: { x: 'And whoever fears Allah — He will make for him a way out and provide for him from where he does not expect. And whoever relies on Allah — He is enough for him.', r: 'Quran 65:2–3' },
        h: { x: 'Whoever holds fast to istighfar, Allah makes for him a way out of every distress, relief from every worry, and provides for him from where he does not expect.', r: 'Abu Dawud 1518' },
        a: { text: 'Start now with 70× istighfar — the key of Nuh for rain, wealth and children.', dhikr: 'istighfar', btn: '70× Istighfar' } }
    ]},
  dua: { prio: 9,
    phrasen: ['dua is not answered','not answered','praying for so long','no answer','how do i make dua','how to make dua','best dua'],
    worte: ['dua','supplication','duas'],
    antworten: [
      { t: 'Your dua is not rejected. It is being processed — by the One who makes no mistakes.',
        e: 'Not a single dua is lost with Allah. Every one is answered in one of three ways: you get it now, or Allah wards off a harm you never saw, or He saves it as a treasure for the Day you need it most. On that Day people will wish NONE of their duas had been answered in this world — because the reward is so immense. The Prophet ﷺ warned of only one thing: impatience — “I prayed and was not answered” (Bukhari 6340). Keep knocking.',
        q: { x: 'And when My servants ask you about Me — indeed I am near. I respond to the call of the caller when he calls upon Me.', r: 'Quran 2:186' },
        h: { x: 'No Muslim makes a dua free of sin and of cutting family ties except that Allah gives him one of three: a swift answer, a treasure in the Hereafter, or an equal harm turned away.', r: 'Musnad Ahmad 11133 — sahih' },
        a: { text: 'Keep knocking at the door. And strengthen your heart meanwhile with La hawla.', dhikr: 'lahawla', btn: '33× La hawla' } },
      { t: 'Dua is an art — and the Prophet ﷺ showed us step by step how Allah loves it most.',
        e: 'Imagine knocking at the door of the most generous King. You don’t run in shouting “give me!” — you greet, you honour, you speak with love. Exactly so: begin with praise (e.g. 10× SubhanAllah, 10× Alhamdulillah, 10× Allahu akbar), then salawat, then call Allah by the name fitting your request — “Ya Razzaq” for provision, “Ya Arhamar-Rahimin” for mercy. Then ask: not demanding, but like a beggar at the door of the Most Generous — yet fully certain that He answers.',
        q: { x: 'And to Allah belong the most beautiful names — so call upon Him by them.', r: 'Quran 7:180' },
        h: { x: 'When one of you prays, let him begin with praising Allah, then send blessings upon the Prophet, then ask whatever he wishes.', r: 'Abu Dawud 1481 — sahih' },
        a: { text: 'The full step-by-step guide with all the best times is in the Knowledge tab (currently in German — translation coming).', view: 'wissen', btn: 'To the guide' } }
    ]},
  waswas: { prio: 8,
    phrasen: ['intrusive thoughts','terrible thoughts','bad thoughts about allah','ugly thoughts','thoughts about god'],
    worte: ['waswas','whispers','whispering','shaytan','satan','doubts'],
    antworten: [
      { t: 'Stop. This flash-thought is not YOURS — and you are not guilty of it.',
        e: 'Such thoughts are like birds flying over your house: you can’t stop them flying, but you decide whether they build a nest. And here is the best part: when the companions told the Prophet ﷺ about such thoughts — ashamed to even speak them — he said: “That is clear faith.” That the thought DISTURBS you proves your heart is alive. The thief only visits the house that has treasure in it.',
        q: { x: 'And if an evil whisper from Satan provokes you, seek refuge in Allah. Indeed, He is Hearing and Knowing.', r: 'Quran 7:200' },
        h: { x: 'Allah has forgiven my ummah what their souls whisper to them, as long as they do not act upon it or speak of it.', r: 'Sahih al-Bukhari 2528, Muslim 127' },
        a: { text: 'Do exactly as taught: say “Aʿudhu billahi minash-shaytanir-rajim”, stop debating the thought, occupy yourself with something else.', dhikr: 'lahawla', btn: '33× La hawla' } }
    ]},
  angst: { prio: 5,
    phrasen: ['afraid of the future','what if','so worried','scared of'],
    worte: ['fear','afraid','worry','worries','anxious','anxiety','panic','stress','future','pressure','exam','overwhelmed'],
    antworten: [
      { t: 'Breathe. Nothing reaches you except what Allah has written for you — and for the believer He writes only good.',
        e: 'Your worries act as if YOU must carry the whole world. You don’t. A child in the back seat doesn’t fear the road — the father is driving. And the Prophet ﷺ told a young man words to memorize: if all of humanity gathered to harm you, they could only harm you with what Allah has already written. The pens are lifted and the pages are dry. And Allah said it twice in a row: with hardship comes ease — one hardship can never beat two eases.',
        q: { x: 'Say: Never will we be struck except by what Allah has decreed for us; He is our protector. And upon Allah let the believers rely.', r: 'Quran 9:51' },
        h: { x: 'Know: if the whole ummah gathered to benefit you, they could only benefit you with what Allah has written for you — and if they gathered to harm you, only with what Allah has written upon you.', r: 'Tirmidhi 2516 — hasan sahih' },
        a: { text: 'Hand over the load now: 33× “La hawla wa la quwwata illa billah”.', dhikr: 'lahawla', btn: '33× La hawla' } }
    ]},
  verzweiflung: { prio: 7,
    phrasen: ['no hope','want to give up',"can't go on",'feel alone','all alone','nobody helps','nobody cares'],
    worte: ['despair','hopeless','give up','pointless','tired','exhausted','depressed','sad','crying','alone','lonely','empty','broken'],
    antworten: [
      { t: '“Do not despair of the mercy of Allah” — that is a direct command from Allah. Out of love.',
        e: 'Do you know to whom Allah says this? To the people with the MOST sins — “those who transgressed against themselves”. If the door stands wide open even for them, how wide is it for you? A dark day is a day — not your life. And when the Prophet ﷺ himself was sad and revelation paused, people said “his Lord has abandoned him” — so Allah sent a whole surah just to say: “Your Lord has not forsaken you, nor does He hate you” (93:3). Your feeling of being abandoned is a feeling — not a fact. The fact is in the Quran.',
        q: { x: 'Say: O My servants who have transgressed against themselves, do not despair of the mercy of Allah. Indeed, Allah forgives all sins.', r: 'Quran 39:53' },
        h: { x: 'Allah says: “I am as My servant thinks of Me, and I am with him when he remembers Me.”', r: 'Hadith Qudsi — Sahih al-Bukhari 7405' },
        a: { text: 'When the heart is heavy, the Prophet ﷺ recommended much salawat — it takes worries away.', dhikr: 'salawat', btn: '10× Salawat' } }
    ]},
  familie: { prio: 4,
    phrasen: ['fight with my','problems with my family','trouble at home'],
    worte: ['family','wife','husband','marriage','children','child','son','daughter','parents','mother','father','brother','sister','divorce','in-laws'],
    antworten: [
      { t: 'Family is test AND blessing at the same time — and your patience there is worship, not defeat.',
        e: 'Allah Himself says in the Quran that there is a test in family and children. So when it is hard at home, you are not automatically doing something wrong — you are in the middle of a test Allah knows and grades. And the Prophet’s ﷺ standard is clear: the best is not the one who shines outside, but the one who is best AT HOME. Every kind word, every swallowed anger counts with Allah.',
        q: { x: 'Our Lord, grant us from among our spouses and offspring comfort to our eyes, and make us a leader for the righteous.', r: 'Quran 25:74' },
        h: { x: 'The best of you are those best to their families — and I am the best of you to my family.', r: 'Tirmidhi 3895 — sahih' },
        a: { text: 'Make ONE small step today: a kind word, a message, a smile. And say the dua of 25:74.', dhikr: 'salawat', btn: '10× Salawat' } }
    ]},
  suende: { prio: 6,
    phrasen: ['made mistakes','did something bad','did haram','committed sins','ashamed of myself','forgive my past','my old life'],
    worte: ['sin','sins','guilt','guilty','repent','repentance','forgive','forgiveness','tawba','mistakes'],
    antworten: [
      { t: 'Your sin is big? Allah’s mercy is bigger. Always. That is not a nice phrase — it is creed.',
        e: 'Allah says in a Hadith Qudsi: “O son of Adam, if you came to Me with sins nearly filling the earth, and met Me without associating anything with Me, I would meet you with as much forgiveness.” An EARTH full of sins against an EARTH full of forgiveness. And more: Allah REJOICES at your return — more than a man in the desert who finds his lost camel with all his provisions after lying down to die. That is how much Allah rejoices when you come back.',
        q: { x: 'And those who, having done something shameful or wronged themselves, remember Allah and ask forgiveness for their sins — and who forgives sins except Allah?', r: 'Quran 3:135' },
        h: { x: 'Allah rejoices more over the repentance of His servant than one of you who finds his lost mount in the desert.', r: 'Sahih al-Bukhari 6309, Muslim 2747' },
        a: { text: 'The Prophet ﷺ — fully forgiven — still made istighfar 70+ times a day (Bukhari 6307). Start now.', dhikr: 'istighfar', btn: '70× Istighfar' } }
    ]},
  qadar: { prio: 5,
    phrasen: ['why me','why always me','why is this happening','missed my chance','too late now','lost everything','tests me so hard'],
    worte: ['fate','destiny','unfair','unjust','unlucky','failed'],
    antworten: [
      { t: 'What missed you could never have hit you. And what hit you could never have missed you.',
        e: 'Do you know the story of Musa and al-Khidr? Al-Khidr makes a hole in the boat of poor people. Looks like damage, right? In truth it was protection: behind them came a king seizing every INTACT boat. The hole saved the boat. Some things in your life that look broken — the missed chance, the rejection, the delay — are in truth a hole Allah drilled to save your boat. You just don’t see it yet.',
        q: { x: 'No disaster strikes upon the earth or among yourselves except that it is in a Book before We bring it into being … so that you not despair over what has escaped you.', r: 'Quran 57:22–23' },
        h: { x: 'Do not say “if only I had done this, then …”, for “if” opens the door to shaytan. Say: “Qaddarallahu wa ma sha’a faʿal” — Allah decreed, and what He willed, He did.', r: 'Sahih Muslim 2664' },
        a: { text: 'Say it out loud once: “Qaddarallahu wa ma sha’a faʿal.” Then close the door of “what if”.', dhikr: 'lahawla', btn: '33× La hawla' } }
    ]},
  krankheit: { prio: 5,
    phrasen: ['i am sick','i am ill','in pain'],
    worte: ['sick','ill','illness','pain','health','hospital','doctor','diagnosis','surgery'],
    antworten: [
      { t: 'Illness takes your strength — but it washes your sins like autumn wind strips leaves from a tree.',
        e: 'The Prophet ﷺ promised: nothing befalls a Muslim — no fatigue, illness, worry, not even a thorn’s prick — except that Allah erases sins by it. Your pain is never wasted with Allah. And important: seeing a doctor is NOT weak tawakkul. The Prophet ﷺ told the man with the camel: “Tie it AND trust in Allah.” Medicine is your tying. Healing still comes only from Him.',
        q: { x: 'And when I am ill, it is He who cures me.', r: 'Quran 26:80' },
        h: { x: 'No fatigue, illness, sorrow, sadness, hurt or distress befalls a Muslim — not even a thorn’s prick — except that Allah expiates some of his sins by it.', r: 'Sahih al-Bukhari 5641' },
        a: { text: 'Put your hand on the pain: 3× “Bismillah”, then 7× “Aʿudhu billahi wa qudratihi min sharri ma ajidu wa uhadhir” (Muslim 2202).', dhikr: 'alhamdu', btn: '33× Alhamdulillah' } }
    ]},
  dank: { prio: 3,
    phrasen: ['went well','it worked','i am happy','so thankful','so grateful','thankful for','grateful for','wish him','wish my brother'],
    worte: ['thanks','thankful','grateful','alhamdulillah','happy','glad','achieved'],
    antworten: [
      { t: 'Alhamdulillah! Hold this moment — gratitude is the key to MORE.',
        e: 'Allah makes you an unconditional promise: “If you are grateful, I will surely give you more.” Gratitude is like watering: what you look at gratefully, grows. And to keep the feeling, the Prophet ﷺ gave a trick: in worldly things look at those below you, not above you — then you suddenly see Allah’s gifts everywhere in your life.',
        q: { x: 'And when your Lord proclaimed: If you are grateful, I will surely increase you.', r: 'Quran 14:7' },
        h: { x: 'Look at those below you and not at those above you — that is more suitable so you do not belittle Allah’s favour upon you.', r: 'Sahih Muslim 2963' },
        a: { text: 'Keep watering: say 33× Alhamdulillah and name concretely what for.', dhikr: 'alhamdu', btn: '33× Alhamdulillah' } }
    ]},
  unmoeglich: { prio: 9,
    phrasen: ['never happen','would never','never work out','never going to work','too late for me','just a dream','stay a dream','impossible for me','not for people like me','be realistic'],
    worte: ['impossible','hopeless','unrealistic','unreachable'],
    antworten: [
      { t: '“Never” is a word for human powers. For the One who says “Be!” — and it is — there is no “never”.',
        e: 'Allah describes His own creating: when He wills a thing, He only says “Kun!” — “Be!” — and it is. No effort, no conditions. Zakariyya was an old man, his wife barren — a child was medically impossible. He made dua anyway. Allah’s answer: “That is easy for Me — I created you before, when you were nothing.” (19:9) And Yahya was born. Your matter may be impossible with people, banks, doctors. But you are not asking people, banks or doctors — you are asking the One who creates from nothing.',
        q: { x: 'His command, when He intends a thing, is only that He says to it: “Be!” — and it is.', r: 'Quran 36:82' },
        h: { x: 'Allah says: “If the first and last of you, human and jinn, stood in one place and all asked Me — and I gave each one his request — it would not decrease My kingdom more than a needle decreases the sea when dipped into it.”', r: 'Hadith Qudsi — Sahih Muslim 2577' },
        a: { text: 'Train the sentence swap: delete “that will never happen” — say out loud: “In sha Allah — my Lord can do anything, even that.” Then tick it on the checklist.', view: 'weg', btn: 'To the checklist' } },
      { t: 'Sara also laughed when the angels announced it. Soon after, she held Ishaq in her arms.',
        e: 'Ibrahim’s wife was old and barren. When the angels announced a son, she LAUGHED — exactly your “that will never happen!” The angels answered: “Do you wonder at the command of Allah?” (11:73). See the pattern: Maryam had a child without a man. Musa stood before the sea, the army behind — everyone cried “we are lost!” He said: “No indeed! My Lord is with me.” (26:62) The sea split. Yusuf lay in a well — years later he ruled Egypt. Allah loves to give exactly where people stamped “impossible” — so that everyone knows afterwards: that was HIM.',
        q: { x: 'Indeed, Allah accomplishes His purpose. Allah has set a measure for all things.', r: 'Quran 65:3' },
        h: { x: 'Allah says: “I am as My servant thinks of Me: if he thinks good of Me, he gets it; and if he thinks evil, he gets that.”', r: 'Musnad Ahmad 9076 — sahih' },
        a: { text: 'Your “impossible” is a diagnosis of YOUR power — not of His. Say 34× “Allahu akbar”: greater than every impossible.', dhikr: 'akbar', btn: '34× Allahu akbar' } }
    ]},
  anleitung: { prio: 10,
    phrasen: ['how do i pray','how to pray','night prayer','last third','tahajjud','pray witr','pray duha','how do i do','morning routine','evening routine','before sleeping','step by step'],
    worte: ['guide','witr','duha','tahajjud','rakat','rakah','sujud'],
    antworten: [
      { t: 'I built guides for exactly this — step by step, with the right duas in the right place.',
        e: 'In the Knowledge tab you’ll find “What would you like to do right now?” at the top — simple guides for the night prayer in the last third (alarm, wudu, 2 rakʿas, dua in sujud, witr — everything in order), Duha, making dua properly, morning and evening routines, before sleeping, and a plan for money worries. Each step is short, and the duas are exactly where you need them. (The guide texts are currently in German — full translation is coming; the pictures of the steps are simple to follow.)',
        q: { x: 'And We revealed to you the message to make clear to the people what was sent down to them.', r: 'Quran 16:44' },
        h: { x: 'Pray as you have seen me pray.', r: 'Sahih al-Bukhari 631' },
        a: { text: 'Open the night-prayer guide — your prayer compass tells you beforehand when the last third begins.', guide: 'nacht', btn: 'To the guide' } }
    ]},
  bedeutung: { prio: 9,
    phrasen: ['what does','what is the meaning','meaning of'],
    worte: ['means','meaning'],
    antworten: [
      { t: 'Beautiful question — dhikr you understand weighs a thousand times more than dhikr you only pronounce.',
        e: 'In the Dhikr tab there is a button “What am I saying? · Understand”: for every dhikr you get the meaning word by word, explained simply, with a picture to imagine and your reward. A taste: “SubhanAllah” means “Allah is perfect — He NEVER makes mistakes.” People forget you, get tired, are unfair. Allah never. So when a mean thought comes like “Allah forgot you”, you call out “SubhanAllah!” — meaning: “No! Allah never forgets!” Say it that way next time — and feel the difference.',
        q: { x: 'And remember the name of your Lord and devote yourself to Him completely.', r: 'Quran 73:8' },
        h: { x: 'Ask Allah with certainty of the answer — and know that Allah does not accept a dua from a heedless, distracted heart.', r: 'Tirmidhi 3479' },
        a: { text: 'Open the Dhikr tab, choose a dhikr and tap “What am I saying? · Understand”.', view: 'dhikr', btn: 'To Understanding' } }
    ]},
  allgemein: { prio: 0, phrasen: [], worte: [],
    antworten: [
      { t: 'I heard you. Read this slowly — it is written for every heart.',
        e: 'Tawakkul does not mean doing nothing. Tawakkul means: you do your best — then you place the RESULT in Allah’s hands and sleep in peace. The farmer sows and waters. But making it grow? No farmer ever could. Your peace begins exactly at that border: between your task (the effort) and Allah’s task (the outcome). If you like, write me more precisely what occupies you — with words like “money”, “fear”, “family”, “dua” or “thoughts” — then I can answer more specifically.',
        q: { x: '… And when you have decided, then rely upon Allah. Indeed, Allah loves those who rely upon Him.', r: 'Quran 3:159' },
        h: { x: 'A man asked: “Shall I tie my camel and trust in Allah, or let it loose and trust?” He said: “Tie it and trust in Allah.”', r: 'Tirmidhi 2517 — hasan' },
        a: { text: 'One minute of dhikr, right now. Your heart is waiting.', dhikr: 'subhan', btn: '33× SubhanAllah' } },
      { t: 'Wherever you stand right now: hearts find rest in the remembrance of Allah. Yours too.',
        e: 'That is not a nice saying — it is a law of Allah, like gravity. As a fish is only calm in water, your heart is only calm in dhikr. Not while scrolling, not while brooding. Try it NOW, not later: one minute, just you and “SubhanAllah”. Your heart will feel the difference immediately.',
        q: { x: 'Verily, in the remembrance of Allah do hearts find rest!', r: 'Quran 13:28' },
        h: { x: 'Allah says: “I am with My servant when he remembers Me and his lips move with My mention.”', r: 'Hadith Qudsi — Ibn Majah 3792 — sahih' },
        a: { text: 'One minute of dhikr, right now.', dhikr: 'subhan', btn: '33× SubhanAllah' } }
    ]}
}
};
